# Generated by Django 5.0.1 on 2026-01-10 23:50

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of the card (e.g., 'Charizard', 'Professor Oak')", max_length=200)),
                ('card_number', models.CharField(help_text="Card number within the set (e.g., '4/102', '001/165')", max_length=20)),
                ('rarity', models.CharField(choices=[('common', 'Common'), ('uncommon', 'Uncommon'), ('rare', 'Rare'), ('holo_rare', 'Holo Rare'), ('ultra_rare', 'Ultra Rare'), ('secret_rare', 'Secret Rare')], default='common', help_text='Rarity of the card', max_length=20)),
                ('card_type', models.CharField(choices=[('pokemon', 'Pokemon'), ('trainer', 'Trainer'), ('energy', 'Energy')], default='pokemon', help_text='Type of card (Pokemon, Trainer, or Energy)', max_length=20)),
                ('image', models.ImageField(blank=True, help_text='Card image (uploaded to S3 in production)', null=True, upload_to='card_images/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Card',
                'verbose_name_plural': 'Cards',
                'db_table': 'cards',
                'ordering': ['pokemon_set', 'card_number'],
            },
        ),
        migrations.CreateModel(
            name='PokemonSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Full name of the Pokemon set (e.g., 'Base Set', 'Scarlet & Violet')", max_length=200)),
                ('set_code', models.CharField(help_text="Unique code/abbreviation for the set (e.g., 'BS', 'SV')", max_length=20, unique=True)),
                ('release_date', models.DateField(blank=True, help_text='Official release date of the set', null=True)),
                ('total_cards', models.PositiveIntegerField(default=0, help_text='Total number of cards in the set')),
                ('series', models.CharField(blank=True, help_text="The series this set belongs to (e.g., 'Original Series', 'Sword & Shield')", max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pokemon Set',
                'verbose_name_plural': 'Pokemon Sets',
                'db_table': 'pokemon_sets',
                'ordering': ['-release_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StreamEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title or name of the stream event', max_length=200)),
                ('stream_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time of the stream')),
                ('platform', models.CharField(choices=[('twitch', 'Twitch'), ('youtube', 'YouTube'), ('other', 'Other')], default='twitch', help_text='Platform where the stream was held', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Notes about the stream')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Stream Event',
                'verbose_name_plural': 'Stream Events',
                'db_table': 'stream_events',
                'ordering': ['-stream_date'],
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(choices=[('mint', 'Mint'), ('near_mint', 'Near Mint'), ('lightly_played', 'Lightly Played'), ('moderately_played', 'Moderately Played'), ('heavily_played', 'Heavily Played'), ('damaged', 'Damaged')], default='near_mint', help_text='Physical condition of the card(s)', max_length=20)),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Number of cards in this condition', validators=[django.core.validators.MinValueValidator(0)])),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, help_text='Price paid for the card(s)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('current_price', models.DecimalField(blank=True, decimal_places=2, help_text='Current market value estimate', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('location', models.CharField(blank=True, help_text="Physical storage location (e.g., 'Binder A, Page 3')", max_length=100)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this inventory item')),
                ('sku', models.CharField(editable=False, help_text='Auto-generated unique Stock Keeping Unit', max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('card', models.ForeignKey(help_text='The card this inventory entry is for', on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='inventory.card')),
            ],
            options={
                'verbose_name': 'Inventory Item',
                'verbose_name_plural': 'Inventory Items',
                'db_table': 'inventory_items',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='card',
            name='pokemon_set',
            field=models.ForeignKey(help_text='The set this card belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='inventory.pokemonset'),
        ),
        migrations.CreateModel(
            name='StreamInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_shown', models.PositiveIntegerField(default=1, help_text='Number of items shown during the stream', validators=[django.core.validators.MinValueValidator(0)])),
                ('quantity_sold', models.PositiveIntegerField(default=0, help_text='Number of items sold during the stream', validators=[django.core.validators.MinValueValidator(0)])),
                ('featured', models.BooleanField(default=False, help_text='Whether this item was featured/highlighted in the stream')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inventory_item', models.ForeignKey(help_text='The inventory item shown in the stream', on_delete=django.db.models.deletion.CASCADE, related_name='stream_appearances', to='inventory.inventoryitem')),
                ('stream_event', models.ForeignKey(help_text='The stream event', on_delete=django.db.models.deletion.CASCADE, related_name='stream_inventory', to='inventory.streamevent')),
            ],
            options={
                'verbose_name': 'Stream Inventory Item',
                'verbose_name_plural': 'Stream Inventory Items',
                'db_table': 'stream_inventory',
                'ordering': ['-stream_event__stream_date'],
            },
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['sku'], name='inventory_sku_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['condition'], name='inventory_condition_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='inventoryitem',
            unique_together={('card', 'condition')},
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['name'], name='card_name_idx'),
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['pokemon_set'], name='card_set_idx'),
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['rarity'], name='card_rarity_idx'),
        ),
    ]
