# Generated by Django 5.0.1 on 2026-01-11 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='image',
            field=models.URLField(blank=True, help_text='Card image URL (CDN or uploaded to S3 in production)', max_length=500, null=True),
        ),
    ]
