# Generated by Django 5.0.1 on 2026-01-15 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_card_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='price_high',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='TCGplayer high price in USD', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='price_low',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='TCGplayer low price in USD', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='price_market',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='TCGplayer market price in USD', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='price_mid',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='TCGplayer mid price in USD', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='price_updated_at',
            field=models.DateTimeField(blank=True, help_text='When the price was last updated from TCGdex', null=True),
        ),
    ]
