# Generated by Django. Add deck field to InventoryItem
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):
    dependencies = [
        ('inventory', '0003_card_price_high_card_price_low_card_price_market_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decks', to='auth.user')),
            ],
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='deck',
            field=models.ForeignKey(blank=True, help_text='The deck this inventory item belongs to (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='inventory.deck'),
        ),
    ]
