# Generated by Django 5.0.1 on 2026-01-22 01:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_deck_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deck',
            options={'ordering': ['name'], 'verbose_name': 'Deck', 'verbose_name_plural': 'Decks'},
        ),
        migrations.AlterField(
            model_name='deck',
            name='name',
            field=models.CharField(help_text='Name of the deck', max_length=100),
        ),
        migrations.AlterField(
            model_name='deck',
            name='owner',
            field=models.ForeignKey(help_text='User who owns this deck', on_delete=django.db.models.deletion.CASCADE, related_name='decks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='deck',
            table='decks',
        ),
    ]
