# Generated by Django 5.0.1 on 2026-01-22 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_deck_options_alter_deck_name_alter_deck_owner_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inventoryitem',
            unique_together={('card', 'condition', 'deck')},
        ),
    ]
