# Generated by Django 5.0.1 on 2026-01-22 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_inventoryitem_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='prestige',
            field=models.CharField(choices=[('common', 'Common'), ('uncommon', 'Uncommon'), ('rare', 'Rare'), ('epic', 'Epic'), ('legendary', 'Legendary')], default='common', help_text='Prestige level of the card in this deck', max_length=20),
        ),
    ]
