# Generated by Django 5.0.1 on 2026-02-05 01:31

import uuid
from django.db import migrations, models


def generate_unique_auction_codes(apps, schema_editor):
    """Generate unique UUIDs for existing inventory items."""
    InventoryItem = apps.get_model('inventory', 'InventoryItem')
    for item in InventoryItem.objects.all():
        item.auction_code = uuid.uuid4()
        item.save(update_fields=['auction_code'])


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_inventoryitem_prestige'),
    ]

    operations = [
        # Step 1: Add auction_code field without unique constraint
        migrations.AddField(
            model_name='inventoryitem',
            name='auction_code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique code for QR/barcode scanning during auctions', null=True),
        ),
        # Step 2: Add sold_at field
        migrations.AddField(
            model_name='inventoryitem',
            name='sold_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the item was sold/removed from auction', null=True),
        ),
        # Step 3: Generate unique UUIDs for existing rows
        migrations.RunPython(generate_unique_auction_codes, migrations.RunPython.noop),
        # Step 4: Make auction_code non-nullable and unique
        migrations.AlterField(
            model_name='inventoryitem',
            name='auction_code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique code for QR/barcode scanning during auctions', unique=True),
        ),
        # Step 5: Add index
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['auction_code'], name='inventory_auction_idx'),
        ),
    ]
