# Generated by Django 5.2.8 on 2026-02-17 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_add_auction_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='prestige',
            field=models.CharField(choices=[('star', 'Star'), ('galaxy', 'Galaxy'), ('cosmos', 'Cosmos'), ('rarion', 'Rarion')], default='star', help_text='Prestige level of the card in this deck', max_length=20),
        ),
    ]
