# Generated by Django 5.2.8 on 2026-02-17 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_update_prestige_choices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='price_high',
        ),
        migrations.RemoveField(
            model_name='card',
            name='price_low',
        ),
        migrations.RemoveField(
            model_name='card',
            name='price_market',
        ),
        migrations.RemoveField(
            model_name='card',
            name='price_mid',
        ),
        migrations.RemoveField(
            model_name='card',
            name='price_updated_at',
        ),
    ]
