# Generated by Django 5.2.8 on 2026-03-21 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_inventoryitem_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='grade',
            field=models.CharField(blank=True, default='', help_text='Card grade (e.g. PSA 10, BGS 9.5, or blank if ungraded)', max_length=50),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='rarity',
            field=models.CharField(blank=True, default='', help_text='Card rarity (e.g. Rare, Ultra Rare, Promo)', max_length=100),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='variance',
            field=models.CharField(blank=True, default='', help_text='Card variance/variation (e.g. Holofoil, Reverse Holofoil)', max_length=100),
        ),
    ]
