# Generated by Django 5.2.8 on 2026-03-21 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_inventoryitem_watchlist_date_added'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inventoryitem',
            unique_together=set(),
        ),
    ]
